markdown: kramdown
theme: minima
title: Progress is inevitable
author:
  name: Jan MinÃ¡rik
  email: jan@minarik.net
description: > # this means to ignore newlines until "show_excerpts:"
  This is a default Evoptima webpage
show_excerpts: false # set to true to show excerpts on the homepage
